apiVersion: 1

deleteDatasources:
  - name: Cortex

datasources:
- name: Cortex
  type: prometheus
  access: proxy
  orgId: 1
  url: http://cortex:9009/api/prom
  basicAuth: false
  isDefault: false
  version: 1
  editable: false
  jsonData:
    httpHeaderName1: 'X-Scope-OrgID'
  secureJsonData:
    httpHeaderValue1: 'fake'
- name: CortexAutoscrape
  type: prometheus
  access: proxy
  orgId: 1
  url: http://cortex:9009/api/prom
  basicAuth: false
  isDefault: false
  version: 1
  editable: false
  jsonData:
    httpHeaderName1: 'X-Scope-OrgID'
  secureJsonData:
    httpHeaderValue1: 'autoscrape'
- name: CortexAvalanche
  type: prometheus
  access: proxy
  orgId: 1
  url: http://cortex:9009/api/prom
  basicAuth: false
  isDefault: false
  version: 1
  editable: false
  jsonData:
    httpHeaderName1: 'X-Scope-OrgID'
  secureJsonData:
    httpHeaderValue1: 'avalanche'
- name: Tempo
  type: tempo
  access: proxy
  orgId: 1
  url: http://tempo:3200
  basicAuth: false
  isDefault: false
  version: 1
  editable: false
  apiVersion: 1
  uid: tempo
- name: Loki
  type: loki
  access: proxy 
  orgId: 1
  url: http://loki:3100
  basicAuth: false
  isDefault: false
  version: 1
  editable: false
  jsonData:
    derivedFields:
      - datasourceUid: tempo
        matcherRegex: tid=(\w+)
        name: TraceID
        url: $${__value.raw}
    httpHeaderName1: 'X-Scope-OrgID'
  secureJsonData:
    httpHeaderValue1: 'fake'
- name: Loki1
  type: loki
  access: proxy
  orgId: 1
  url: http://loki:3100
  basicAuth: false
  isDefault: false
  version: 1
  editable: false
  jsonData:
    derivedFields:
      - datasourceUid: tempo
        matcherRegex: tid=(\w+)
        name: TraceID
        url: $${__value.raw}
    httpHeaderName1: 'X-Scope-OrgID'
  secureJsonData:
    httpHeaderValue1: 'loki1'
- name: Loki2
  type: loki
  access: proxy
  orgId: 1
  url: http://loki:3100
  basicAuth: false
  isDefault: false
  version: 1
  editable: false
  jsonData:
    derivedFields:
      - datasourceUid: tempo
        matcherRegex: tid=(\w+)
        name: TraceID
        url: $${__value.raw}
    httpHeaderName1: 'X-Scope-OrgID'
  secureJsonData:
    httpHeaderValue1: 'loki2'